const $=(q,el=document)=>el.querySelector(q);const $$=(q,el=document)=>[...el.querySelectorAll(q)];
const state={niches:JSON.parse(localStorage.getItem('nm_niches')||'[]'),used:new Set(JSON.parse(localStorage.getItem('nm_used')||'[]')),currentNiche:null,keywords:[],page:0,pageSize:12};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.tab).classList.add('active')});
document.addEventListener('touchmove',()=>{if(document.scrollingElement.scrollLeft!==0)document.scrollingElement.scrollLeft=0},{passive:true});
function saveN(){localStorage.setItem('nm_niches',JSON.stringify(state.niches))}function saveU(){localStorage.setItem('nm_used',JSON.stringify([...state.used]))}
function renderN(){const list=$('#nicheList');list.innerHTML='';if(!state.niches.length){list.innerHTML='<li><span class="txt muted">Add a niche above to get started.</span></li>';return}state.niches.forEach((n,i)=>{const li=document.createElement('li');li.innerHTML=`<span class='txt'>${n}</span><div class='row g8'><button class='btn' data-load='${i}'>Load</button><button class='btn ghost' data-del='${i}'>Del</button></div>`;list.appendChild(li)});$$('[data-del]').forEach(b=>b.onclick=()=>{state.niches.splice(+b.dataset.del,1);saveN();renderN()});$$('[data-load]').forEach(b=>b.onclick=()=>{const n=state.niches[+b.dataset.load];state.currentNiche=n;state.page=0;state.keywords=[];loadK(n,true)})}
$('#addNicheBtn').onclick=()=>{const v=$('#nicheInput').value.trim();if(!v)return;if(!state.niches.includes(v))state.niches.unshift(v);$('#nicheInput').value='';saveN();renderN()}
async function fakeAPI(t){const base=['best {t} 2025','{t} for beginners','{t} guide','how to {t}','{t} checklist','{t} tools','{t} vs alternatives','{t} cost','{t} near me','{t} mistakes'];t=t.toLowerCase().trim();return base.map((s,i)=>{const term=s.replaceAll('{t}',t);return{term,score:62+((i*7)%33),intent:i%3?'Informational':'Commercial',related:['template','software','free','examples','2025','vs','beginner','advanced'].map(r=>term+' '+r)}})}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function renderK(reset=false){const wrap=$('#kwCards');if(reset)wrap.innerHTML='';const start=state.page*state.pageSize;const items=state.keywords.slice(start,start+state.pageSize);if(!items.length&&state.page===0){wrap.innerHTML='<div class="muted">No keywords yet.</div>';return}const hide=$('#filterUsed').checked;items.forEach(row=>{if(hide&&state.used.has(row.term.toLowerCase()))return;const card=document.createElement('div');card.className='kw-card';card.innerHTML=`<div><div style='font-weight:800;margin-bottom:4px'>${esc(row.term)}</div><div class='kw-rel'>${row.related.slice(0,8).map(r=>`<span class='bubble' data-drill='${encodeURIComponent(r)}'>${esc(r)}</span>`).join('')}</div></div><div class='kw-meta'><span class='badge score'>Score ${row.score}</span><span class='badge'>${row.intent}</span><button class='btn ghost' data-open='${encodeURIComponent(row.term)}'>Open</button><button class='btn primary' data-use='${encodeURIComponent(row.term)}'>Use</button></div>`;wrap.appendChild(card)});$$('[data-drill]').forEach(b=>b.onclick=()=>loadK(decodeURIComponent(b.dataset.drill),true));$$('[data-open]').forEach(b=>b.onclick=()=>openCreate(state.currentNiche||'(niche)',decodeURIComponent(b.dataset.open)));$$('[data-use]').forEach(b=>b.onclick=()=>{const k=decodeURIComponent(b.dataset.use).toLowerCase();state.used.add(k);saveU();openCreate(state.currentNiche||'(niche)',decodeURIComponent(b.dataset.use))})}
async function loadK(topic,reset=false){$('#spinner').classList.remove('hidden');try{const rows=await fakeAPI(topic);state.keywords=reset?rows:state.keywords.concat(rows);renderK(reset)}catch(e){console.error(e)}finally{$('#spinner').classList.add('hidden')}}
function openCreate(n,k){$$('.tab').forEach(x=>x.classList.remove('active'));$$('[data-tab]').find(b=>b.dataset.tab==='create')?.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-create').classList.add('active');$('#selNiche').value=n;$('#selKeyword').value=k}
function genBlog(n,k){const d=new Date().toLocaleDateString();return `<!-- Ads slots --><div class='adsense-slot' data-ad='top'></div>\n# ${k}\n*Updated ${d}*\n\n**In ${n}**, this post covers:\n- Basics\n- Steps\n- Tools\n\n## Steps\n1. Prep\n2. Execute\n3. Optimize\n\n<div class='adsense-slot' data-ad='end'></div>\n`}function genEbook(n,k){const y=new Date().getFullYear();return `# The ${k.replace(/\b\w/g,m=>m.toUpperCase())} Playbook (${y})\n\n**For ${n}**\n\n## 1. Foundations\n## 2. Toolkit\n## 3. System\n## 4. Monetization\n`}function genShorts(k){return `Shorts — ${k}\nHook → Step1 → Step2 → CTA`}function genPins(k){return `Pins — ${k}\n- Checklist\n- Before/After\n- 3 Mistakes`}async function unsplash(q){return Array.from({length:6}).map((_,i)=>`https://source.unsplash.com/600x400/?${encodeURIComponent(q)}&sig=${Date.now()+i}`)}
$('#btnBlog').onclick=()=>{$('#output').value=genBlog($('#selNiche').value,$('#selKeyword').value)};$('#btnEbook').onclick=()=>{$('#output').value=genEbook($('#selNiche').value,$('#selKeyword').value)};$('#btnShorts').onclick=()=>{$('#output').value=genShorts($('#selKeyword').value)};$('#btnPins').onclick=()=>{$('#output').value=genPins($('#selKeyword').value)}
$('#btnImg').onclick=async()=>{const q=$('#imgQuery').value.trim()||$('#selKeyword').value.trim()||'blog';const urls=await unsplash(q);$('#imgStrip').innerHTML=urls.map(u=>`<img src='${u}' alt=''>`).join('')}
$('#btnAff').onclick=async()=>{const q=$('#affQuery').value.trim()||($('#selKeyword').value.trim()+' affiliate');const results=[`https://www.google.com/search?q=${encodeURIComponent(q+' affiliate program')}`,`https://www.google.com/search?q=${encodeURIComponent(q+' referral')}`];$('#affList').innerHTML=results.map(u=>`<li><a href='${u}' target='_blank' rel='noopener'>${u}</a></li>`).join('')}
$('#btnCopy').onclick=async()=>{await navigator.clipboard.writeText($('#output').value||'');alert('Copied')}
$('#btnMd').onclick=()=>{const blob=new Blob([$('#output').value||''],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('#selKeyword').value||'post')+'.md');a.click()}
$('#btnWP').onclick=async()=>{const url=(($('#wpUrl').value||'').replace(/\/$/,'')||'')+'/posts';const user=$('#wpUser').value,pass=$('#wpPass').value;if(!url||!user||!pass){alert('Enter WP URL, user, app password');return}const auth=btoa(`${user}:${pass}`);const title=$('#selKeyword').value||'Draft from NicheMiner';const content=$('#output').value||genBlog($('#selNiche').value,$('#selKeyword').value);try{const res=await fetch(url,{method:'POST',headers:{'Authorization':'Basic '+auth,'Content-Type':'application/json'},body:JSON.stringify({title,content,status:'draft'})});if(!res.ok)throw new Error(await res.text());const data=await res.json();alert('Draft created: '+(data?.link||''))}catch(e){alert('WP error: '+e.message)}}
$('#agg').oninput=e=>$('#aggVal').textContent=e.target.value;$('#btnMentor').onclick=()=>{const a=+$('#agg').value;const plan=a>=8?'Post daily blogs + shorts + pins. Target 3 new niches/week.':a>=5?'Post 3x/week blogs, 2x shorts. Expand 1 niche/week.':'Post 1–2 blogs/week. Tighten internal links; optimize top 5 posts.';$('#aiMentor').value=plan+'\n\nNext: Refresh old posts with new images & affiliate CTAs.'}
const sites=[];function renderSites(){const ul=$('#siteList');ul.innerHTML='';sites.forEach(s=>ul.innerHTML+=`<li>${s.name} — $${s.rev.toFixed(2)} / ${s.clk} clicks</li>`);const rev=sites.reduce((a,s)=>a+s.rev,0),clk=sites.reduce((a,s)=>a+s.clk,0);$('#kpiRev').textContent='$'+rev.toFixed(2);$('#kpiClk').textContent=String(clk);$('#kpiRPM').textContent='$'+(clk?(rev/clk*1000).toFixed(2):'0.00')}
$('#btnAddSite').onclick=()=>{const n=$('#siteName').value.trim();const r=parseFloat($('#siteRevenue').value||'0')||0;const c=parseInt($('#siteClicks').value||'0')||0;if(!n)return;sites.push({name:n,rev:r,clk:c});renderSites()}
renderN();