const $=(q,el=document)=>el.querySelector(q); const $$=(q,el=document)=>[...el.querySelectorAll(q)];
const state={niches:JSON.parse(localStorage.getItem('nm_niches')||'[]'),used:new Set(JSON.parse(localStorage.getItem('nm_used')||'[]')),currentNiche:null,keywords:[],page:0,pageSize:12,sb:{url:localStorage.getItem('nm_sb_url')||'',key:localStorage.getItem('nm_sb_key')||''}};
$$('.tab').forEach(b=> b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.view').forEach(v=>v.classList.remove('active')); $('#view-'+b.dataset.tab).classList.add('active')});
$('#fab').onclick=()=> $('#drawer').classList.add('open'); $('#drawerBtn').onclick=()=> $('#drawer').classList.add('open'); $('#drawerClose').onclick=()=> $('#drawer').classList.remove('open');
$('#btnSaveSb').onclick=()=>{state.sb.url=$('#sbUrl').value.trim();state.sb.key=$('#sbKey').value.trim(); if(state.sb.url)localStorage.setItem('nm_sb_url',state.sb.url); if(state.sb.key)localStorage.setItem('nm_sb_key',state.sb.key); alert('Supabase saved locally')};
$('#sbUrl').value=state.sb.url; $('#sbKey').value=state.sb.key;
function saveN(){localStorage.setItem('nm_niches',JSON.stringify(state.niches))} function saveU(){localStorage.setItem('nm_used',JSON.stringify([...state.used]))}
function renderN(){const list=$('#nicheList'); list.innerHTML=''; if(!state.niches.length){list.innerHTML='<li><span class="txt muted">Add a niche above to get started.</span></li>';return} state.niches.forEach((n,i)=>{const li=document.createElement('li'); li.innerHTML=`<span class='txt'>${n}</span><div class='row g8'><button class='btn' data-load='${i}'>Load</button><button class='btn ghost' data-del='${i}'>Del</button></div>`; list.appendChild(li)}); $$('[data-del]').forEach(b=> b.onclick=()=>{state.niches.splice(+b.dataset.del,1);saveN();renderN()}); $$('[data-load]').forEach(b=> b.onclick=()=>{const n=state.niches[+b.dataset.load]; state.currentNiche=n; state.page=0; state.keywords=[]; loadKeywords(n,true)})}
$('#addNicheBtn').onclick=()=>{const v=$('#nicheInput').value.trim(); if(!v)return; if(!state.niches.includes(v))state.niches.unshift(v); $('#nicheInput').value=''; saveN(); renderN()}
async function fetchDDG(q){const r=await fetch(`https://duckduckgo.com/ac/?q=${encodeURIComponent(q)}`); if(!r.ok) throw new Error('DDG '+r.status); return (await r.json()).map(x=>x.phrase).filter(Boolean)}
async function fetchWiki(q){const r=await fetch(`https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&origin=*&srsearch=${encodeURIComponent(q)}`); if(!r.ok) throw new Error('WIKI '+r.status); const d=await r.json(); return (d?.query?.search||[]).map(s=>({title:s.title,wordcount:s.wordcount||0}))}
async function fetchYTAuto(q){try{const r=await fetch(`https://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q=${encodeURIComponent(q)}`); if(!r.ok) return []; const d=await r.json(); return d?.[1]||[]}catch{return []}}
function score(term,wiki){let s=50;const t=term.toLowerCase();const hit=wiki.find(w=>t.includes(w.title.toLowerCase())); if(hit)s+=Math.min(30,Math.round(hit.wordcount/200)); if(term.length<20)s+=5; if(/\bhow to\b|guide|best|vs|near me|checklist/.test(t))s+=5; return Math.max(40,Math.min(95,s))}
async function liveKeywordAPI(topic){const [ddg,wiki,yta]=await Promise.all([fetchDDG(topic),fetchWiki(topic),fetchYTAuto(topic)]); const set=new Set();const terms=[];const push=t=>{const k=(t||'').trim().toLowerCase(); if(!k||set.has(k))return; set.add(k); terms.push(t.trim())}; ddg.forEach(push); yta.forEach(push); wiki.forEach(w=>push(w.title)); const pats=[' template',' software',' free',' examples',' checklist',' 2025',' vs',' beginner',' advanced']; return terms.slice(0,60).map(t=>({term:t,score:score(t,wiki),intent:/buy|price|cost|near me|software|tool/.test(t.toLowerCase())?'Commercial':'Informational',related:pats.map(p=>t+p)}))}
function renderKeywords(reset=false){const ul=$('#kwList'); if(reset) ul.innerHTML=''; const start=state.page*state.pageSize; const items=state.keywords.slice(start,start+state.pageSize); if(!items.length&&state.page===0){ul.innerHTML='<li class="muted" style="padding:8px 2px">No keywords yet.</li>';return} const hide=$('#filterUsed').checked; items.forEach(row=>{if(hide&&state.used.has(row.term.toLowerCase()))return; const li=document.createElement('li'); li.className='kw-item'; li.innerHTML=`<div class='kw-head'><span class='chev'>▶</span><div class='kw-title'>${esc(row.term)}</div><div class='kw-meta'><span class='badge'>Score ${row.score}</span><span class='badge'>${row.intent}</span><button class='btn ghost' data-open='${encodeURIComponent(row.term)}'>Open</button><button class='btn primary' data-use='${encodeURIComponent(row.term)}'>Use</button></div></div><div class='kw-body'><div class='kw-inner'><div class='kw-related'>${row.related.slice(0,8).map(r=>`<div class='rel-row'><span>${esc(r)}</span><div class='row g8'><button class='btn ghost' data-drill='${encodeURIComponent(r)}'>Drill</button><button class='btn' data-open='${encodeURIComponent(r)}'>Open</button><button class='btn primary' data-use='${encodeURIComponent(r)}'>Use</button></div></div>`).join('')}</div></div></div>`; ul.appendChild(li)}); $$('.kw-head',ul).forEach(h=>{h.onclick=()=>{const it=h.closest('.kw-item'); if(it.classList.contains('open')){it.classList.remove('open');return} $$('#kwList .kw-item.open').forEach(x=>x.classList.remove('open')); it.classList.add('open')}}); $$('[data-drill]').forEach(b=> b.onclick=()=> loadKeywords(decodeURIComponent(b.dataset.drill),true)); $$('[data-open]').forEach(b=> b.onclick=()=> openCreate(state.currentNiche||'(niche)', decodeURIComponent(b.dataset.open))); $$('[data-use]').forEach(b=> b.onclick=()=> markUsed(decodeURIComponent(b.dataset.use)) )}
$('#collapseAllBtn').onclick=()=> $$('#kwList .kw-item.open').forEach(x=>x.classList.remove('open'));
async function loadKeywords(topic,reset=false){$('#spinner').classList.remove('hidden'); try{const rows=await liveKeywordAPI(topic); state.keywords=reset?rows:state.keywords.concat(rows); renderKeywords(reset)}catch(e){console.error(e); alert('Keyword fetch error: '+e.message)} finally{$('#spinner').classList.add('hidden')}}
async function supaInsertUsed(niche,keyword){if(!state.sb.url||!state.sb.key)return false; try{const r=await fetch(`${state.sb.url}/rest/v1/used_keywords`,{method:'POST',headers:{'apikey':state.sb.key,'Authorization':'Bearer '+state.sb.key,'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'},body:JSON.stringify({niche,keyword,site:'',created_at:new Date().toISOString()})}); return r.ok}catch(e){console.warn('Supabase error',e);return false}}
async function markUsed(term){const k=term.toLowerCase(); if(state.used.has(k)){openCreate(state.currentNiche||'(niche)',term);return} state.used.add(k); saveU(); await supaInsertUsed(state.currentNiche||'(niche)',term); openCreate(state.currentNiche||'(niche)',term)}
function openCreate(n,k){$$('.tab').forEach(x=>x.classList.remove('active')); $$('[data-tab]').find(b=>b.dataset.tab==='create')?.classList.add('active'); $$('.view').forEach(v=>v.classList.remove('active')); $('#view-create').classList.add('active'); $('#selNiche').value=n; $('#selKeyword').value=k}
function genBlog(n,k){const d=new Date().toLocaleDateString();return `<!-- Ad placeholders --><div class="adsense-slot" data-ad="top"></div>\n# ${k}\n*Updated ${d}*\n\n**In ${n}**, this post covers:\n- Basics\n- Steps\n- Tools\n\n## Steps\n1. Prep\n2. Execute\n3. Optimize\n\n<div class="adsense-slot" data-ad="end"></div>\n`}
function genEbook(n,k){const y=new Date().getFullYear();return `# The ${cap(k)} Playbook (${y})\n\n**For ${n}**\n\n## 1. Foundations\n## 2. Toolkit\n## 3. System\n## 4. Monetization\n## 5. Case Studies\n## 6. Compliance\n`}
function genShorts(k){return `Shorts — ${k}\nHook → Step1 → Step2 → Bonus → CTA`}
function genPins(k){return `Pins — ${k}\n- Checklist\n- Before/After\n- 3 Mistakes\n- Minimal`}
async function unsplash(q){return Array.from({length:6}).map((_,i)=>`https://source.unsplash.com/600x400/?${encodeURIComponent(q)}&sig=${Date.now()+i}`)}
$('#btnBlog').onclick=()=> $('#output').value=genBlog($('#selNiche').value,$('#selKeyword').value);
$('#btnEbook').onclick=()=> $('#output').value=genEbook($('#selNiche').value,$('#selKeyword').value);
$('#btnShorts').onclick=()=> $('#output').value=genShorts($('#selKeyword').value);
$('#btnPins').onclick=()=> $('#output').value=genPins($('#selKeyword').value);
$('#btnImg').onclick=async()=>{const q=$('#imgQuery').value.trim()||$('#selKeyword').value.trim()||'blog'; const urls=await unsplash(q); $('#imgStrip').innerHTML=urls.map(u=>`<img src='${u}' alt=''>`).join('')};
$('#btnAff').onclick=async()=>{const q=$('#affQuery').value.trim()||($('#selKeyword').value.trim()+' affiliate'); const u=[`https://www.google.com/search?q=${encodeURIComponent(q+' affiliate program')}`,`https://www.google.com/search?q=${encodeURIComponent(q+' referral program')}`,`https://www.google.com/search?q=${encodeURIComponent(q+' coupon partner')}`]; $('#affList').innerHTML=u.map(x=>`<li><a href='${x}' target='_blank' rel='noopener'>${x}</a></li>`).join('')};
$('#btnCopy').onclick=async()=>{await navigator.clipboard.writeText($('#output').value||''); alert('Copied')};
$('#btnMd').onclick=()=>{const blob=new Blob([$('#output').value||''],{type:'text/markdown'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=(($('#selKeyword').value||'post')+'.md'); a.click()};
$('#btnWP').onclick=async()=>{const url=(($('#wpUrl').value||'').replace(/\/$/,'')||'')+'/posts'; const user=$('#wpUser').value, pass=$('#wpPass').value; if(!url||!user||!pass){alert('Enter WP URL, user, app password');return} const auth=btoa(`${user}:${pass}`); const title=$('#selKeyword').value||'Draft from NicheMiner'; const content=$('#output').value||genBlog($('#selNiche').value,$('#selKeyword').value); try{const res=await fetch(url,{method:'POST',headers:{'Authorization':'Basic '+auth,'Content-Type':'application/json'},body:JSON.stringify({title,content,status:'draft'})}); if(!res.ok) throw new Error(await res.text()); await markUsed(title); const data=await res.json(); alert('Draft created: '+(data?.link||''))}catch(e){alert('WP error: '+e.message)}};
$('#agg').oninput=e=> $('#aggVal').textContent=e.target.value; $('#btnMentor').onclick=()=>{const a=+$('#agg').value; const plan=a>=8?'Post daily blogs + shorts + pins. Target 3 new niches/week.':a>=5?'Post 3x/week blogs, 2x shorts. Expand 1 niche/week.':'Post 1–2 blogs/week. Tighten internal links; optimize top 5 posts.'; $('#aiMentor').value=plan+'\n\nNext: Refresh old posts with new images & affiliate CTAs.'};
const sites=[]; function renderSites(){const ul=$('#siteList'); ul.innerHTML=''; sites.forEach(s=> ul.innerHTML+=`<li>${s.name} — $${s.rev.toFixed(2)} / ${s.clk} clicks</li>`); const rev=sites.reduce((a,s)=>a+s.rev,0),clk=sites.reduce((a,s)=>a+s.clk,0); $('#kpiRev').textContent='$'+rev.toFixed(2); $('#kpiClk').textContent=String(clk); $('#kpiRPM').textContent='$'+(clk?(rev/clk*1000).toFixed(2):'0.00')}
$('#btnAddSite').onclick=()=>{const n=$('#siteName').value.trim(); const r=parseFloat($('#siteRevenue').value||'0')||0; const c=parseInt($('#siteClicks').value||'0')||0; if(!n)return; sites.push({name:n,rev:r,clk:c}); renderSites()}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))} function cap(s){return s.replace(/\b\w/g,m=>m.toUpperCase())}
renderN();
