const state={niches:JSON.parse(localStorage.getItem('nm_niches')||'[]'),keywords:[],page:0,pageSize:10,env:{VITE_SUPABASE_URL:window.ENV?.VITE_SUPABASE_URL||localStorage.getItem('nm_sb_url')||'',VITE_SUPABASE_KEY:window.ENV?.VITE_SUPABASE_KEY||localStorage.getItem('nm_sb_key')||'',WP_URL:localStorage.getItem('nm_wp_url')||'',WP_TOKEN:localStorage.getItem('nm_wp_token')||''}};
const $=s=>document.querySelector(s);const nicheListEl=$('#nicheList');const kwTableEl=$('#keywordTable');function toast(m){console.log('[NM]',m)}
function saveNiches(){localStorage.setItem('nm_niches',JSON.stringify(state.niches))}
function renderNiches(){if(!state.niches.length){nicheListEl.innerHTML=`<li class="muted" style="grid-column:1/-1">Add a niche and tap <em>Load keywords</em>.</li>`;return}
nicheListEl.innerHTML=state.niches.map((n,i)=>`<li><span class="chip" title="${n}">${n}</span><div style="display:flex;gap:6px"><button class="btn ghost" data-load="${i}">Load keywords</button><button class="icon" data-del="${i}" title="Remove">🗑</button></div></li>`).join('');
nicheListEl.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const i=+b.dataset.del;state.niches.splice(i,1);saveNiches();renderNiches()});
nicheListEl.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const i=+b.dataset.load;loadKeywords(state.niches[i],true)})}
function keywordCardRow(r){const rel=(r.related||[]).slice(0,8).map(x=>`<span class="bubble" data-bubble="${encodeURIComponent(x)}">${x}</span>`).join('');return `<div class="kw-card"><div><div style="font-weight:700;margin-bottom:4px">${r.term}</div><div class="kw-related">${rel}</div></div><div class="meta"><span class="badge score">Score ${r.score??'–'}</span><span class="badge">${r.intent||'—'}</span><button class="btn ghost" data-drill="${encodeURIComponent(r.term)}">Drill down</button><button class="btn primary" data-save="${encodeURIComponent(r.term)}">Use</button></div></div>`}
function renderKeywords(reset=false){if(reset)kwTableEl.innerHTML='';const start=state.page*state.pageSize;const slice=state.keywords.slice(start,start+state.pageSize);if(!slice.length&&state.page===0){kwTableEl.innerHTML=`<div class="muted">No keywords yet.</div>`;return}kwTableEl.insertAdjacentHTML('beforeend',slice.map(keywordCardRow).join(''));kwTableEl.querySelectorAll('[data-bubble]').forEach(e=>e.onclick=()=>loadKeywords(decodeURIComponent(e.dataset.bubble),true));kwTableEl.querySelectorAll('[data-drill]').forEach(e=>e.onclick=()=>loadKeywords(decodeURIComponent(e.dataset.drill),true));kwTableEl.querySelectorAll('[data-save]').forEach(e=>e.onclick=()=>markUsed(decodeURIComponent(e.dataset.save)))};
async function fakeKeywordAPI(topic){const seed=topic.replace(/\s+/g,'-').toLowerCase();const v=[`best ${seed} 2025`,`${seed} for beginners`,`${seed} near me`,`${seed} cheap`,`${seed} vs alternatives`,`${seed} guide`,`${seed} checklist`,`how to ${seed}`,`${seed} mistakes`,`${seed} reddit`];return v.map((t,i)=>({term:t,score:60+((i*7)%35),intent:i%3?'Informational':'Commercial',related:v.filter(x=>x!==t)}))}
async function loadKeywords(topic,reset=false){if(reset){state.page=0;state.keywords=[];kwTableEl.innerHTML=''}$('#spinner').classList.remove('hidden');try{const rows=await fakeKeywordAPI(topic);state.keywords=state.keywords.concat(rows);renderKeywords(reset)}catch(e){console.error(e)}finally{$('#spinner').classList.add('hidden')}}
function markUsed(term){const key='nm_used_terms';const set=new Set(JSON.parse(localStorage.getItem(key)||'[]'));if(set.has(term)){toast('Already saved.');return}set.add(term);localStorage.setItem(key,JSON.stringify([...set]));toast('Saved '+term)}
const drawer=$('#drawer');$('#fab').onclick=()=>drawer.classList.add('open');$('#drawerClose').onclick=()=>drawer.classList.remove('open');$('#settingsBtn').onclick=()=>drawer.classList.add('open');
$('#saveEnvBtn').onclick=()=>{const url=$('#supabaseUrl').value.trim();const key=$('#supabaseKey').value.trim();const wpUrl=$('#wpUrl').value.trim();const wpToken=$('#wpToken').value.trim();if(url)localStorage.setItem('nm_sb_url',url);if(key)localStorage.setItem('nm_sb_key',key);if(wpUrl)localStorage.setItem('nm_wp_url',wpUrl);if(wpToken)localStorage.setItem('nm_wp_token',wpToken);state.env.VITE_SUPABASE_URL=localStorage.getItem('nm_sb_url')||'';state.env.VITE_SUPABASE_KEY=localStorage.getItem('nm_sb_key')||'';state.env.WP_URL=localStorage.getItem('nm_wp_url')||'';state.env.WP_TOKEN=localStorage.getItem('nm_wp_token')||'';toast('Saved settings locally.')};
(function hydrate(){['supabaseUrl','supabaseKey','wpUrl','wpToken'].forEach(id=>{const map={supabaseUrl:'nm_sb_url',supabaseKey:'nm_sb_key',wpUrl:'nm_wp_url',wpToken:'nm_wp_token'};const v=localStorage.getItem(map[id])||'';document.getElementById(id).value=v});})();$('#addNicheBtn').onclick=()=>{const val=$('#nicheInput').value.trim();if(!val)return;state.niches.push(val);saveNiches();renderNiches();$('#nicheInput').value=''};$('#refreshBtn').onclick=()=>location.reload();$('#loadMoreBtn').onclick=()=>{state.page++;renderKeywords(false)};$('#runPromptBtn').onclick=()=>{const p=$('#aiPrompt').value.trim();if(!p)return;const lines=p.split('\n').map(s=>s.trim()).filter(Boolean);if(lines.length){state.niches=[...new Set([...state.niches,...lines])];saveNiches();renderNiches();toast('Imported niches')}};function makeEpub(title,author,chapters){const md=`# ${title}\n\n**Author:** ${author}\n\n---\n\n`+chapters.map((c,i)=>`## ${i+1}. ${c.heading}\n\n${c.body}\n`).join('\n\n');const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(title||'ebook')+'.md';a.click()}$('#ebookFromKeywords').onclick=()=>{const chapters=state.keywords.slice(0,10).map(k=>({heading:k.term,body:`Outline: ${k.related?.slice(0,5).join(', ')||''}`}));$('#ebookOutline').value=chapters.map(c=>`- ${c.heading}: ${c.body}`).join('\n')};$('#exportEpubBtn').onclick=()=>{const title=$('#ebookTitle').value||'My Niche eBook';const author=$('#ebookAuthor').value||'NicheMiner';const lines=$('#ebookOutline').value.split('\n').filter(Boolean);const chapters=lines.map(ln=>({heading:ln.replace(/^-+\s*/,'').split(':')[0],body:ln.split(':').slice(1).join(':').trim()||'Content here.'}));makeEpub(title,author,chapters)};$('#exportCsvBtn').onclick=()=>{const rows=state.keywords.map(k=>[k.term,k.score??'',k.intent??''].join(','));const csv='term,score,intent\n'+rows.join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='keywords.csv';a.click()};$('#clearCacheBtn').onclick=()=>{['nm_niches','nm_sb_url','nm_sb_key','nm_wp_url','nm_wp_token','nm_used_terms'].forEach(k=>localStorage.removeItem(k));toast('Cleared local cache.')};renderNiches();